sudo: false

language: c++

notifications:
    email: false

os: linux

matrix:
  include:
    - compiler: clang
      env: CLANG_VERSION=3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - libprotobuf-dev
            - protobuf-compiler
    - compiler: clang
      env: CLANG_VERSION=3.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise # latest
          packages:
            - clang-3.7
            - libprotobuf-dev
            - protobuf-compiler
    - compiler: gcc
      env: GCC_VERSION=4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - gcc-4.9
            - libprotobuf-dev
            - protobuf-compiler

before_install:
  - |
    if [ ${CC} == 'clang' ]; then
        export CC="/usr/lib/llvm-${CLANG_VERSION}/bin/clang"
        export CXX="/usr/lib/llvm-${CLANG_VERSION}/bin/clang++"
    elif [ ${CC} == 'gcc' ]; then
        export CC="/usr/bin/gcc-${GCC_VERSION}"
        export CXX="/usr/bin/g++-${GCC_VERSION}"
    fi
    eval "${CC} --version"
    eval "${CXX} --version"

    sed -i.backup 's/c++11/c++14/' src/third_party/g3log/Build.cmake
    if [ ${CC} == 'clang' ]; then
        sed -i.backup '19s/libc++/libstdc++/' src/third_party/g3log/Build.cmake
    fi

before_script:
    - cmake .

script:
    - make

branches:
    only:
        - master
