sudo: false
language: c++

notifications:
  email: false

os: linux

addons:
  packages:
    - libprotobuf-dev
    - protobuf-compiler

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - binutils
            - cpp-5
            - gcc-5
            - libc6
            - libcc1-0
            - libgcc-5-dev
            - libgcc1
            - libgmp10
            - libisl10
            - libmpc2
            - libmpfr4
            - libstdc++6
            - zlib1g
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.6
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.6
            - libclang-3.6-dev
            - libclang-common-3.6-dev
            - libgcc-4.9-dev
            - libllvm3.6
            - libobjc-4.9-dev
            - libstdc++6

before_script:
    - cmake .

script:
    - make

branches:
    only:
        - master
