language: c++

notifications:
    email: false

os:
    - linux

compiler:
    - clang
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.6
            - cmake
            - gcc-5
            - libprotobuf-dev
            - protobuf-compiler


before_script:
    - cmake .

script:
    - make

branches:
    only:
        - master
