sudo: false

language: c++

notifications:
    email: false

os: linux

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - libprotobuf-dev
            - protobuf-compiler
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - gcc-5
            - libprotobuf-dev
            - protobuf-compiler

before_install:
  - |
    if [ ${CC} == 'clang' ]; then
        export CC=/usr/lib/llvm-3.6/bin/clang
        export CXX=/usr/lib/llvm-3.6/bin/clang++
    elif [ ${CC} == 'gcc' ]; then
        export CC=/usr/bin/gcc-5;
        export CXX=/usr/bin/g++-5;
    fi
    eval "${CC} --version"
    eval "${CXX} --version"

before_script:
    - cmake .

script:
    - make

branches:
    only:
        - master
