sudo: false
language: c++

notifications:
  email: false

os: linux

compiler:
    - clang
    - gcc


matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - libprotobuf-dev
            - protobuf-compiler
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - libprotobuf-dev
            - protobuf-compiler

before_script:
    - cmake .

script:
    - make

branches:
    only:
        - master
