language: cpp
notifications:
    email: false
os:
    - linux
    - osx
compiler:
    - clang
    - gcc


before_install:
    - echo ${LANG}
    - echo ${LC_ALL}
    - if [ ${TRAVIS_OS_NAME} == 'linux' ]; then ./scripts/install_deps/linux.sh; fi
    - if [ ${TRAVIS_OS_NAME} == 'osx' ]; then ./scripts/install_deps/osx.sh; fi
before_script:
    - cmake .
script:
    - make

branches:
    only:
        - master
