sudo: required

language: c++

notifications:
    email: false

os: linux

compiler:
  - clang
  - gcc


before_install:
  - if [ ${TRAVIS_OS_NAME} == 'linux' ]; then ./scripts/install_deps/linux.sh; fi
  - eval "${CXX} --version"
  - eval "${CC} --version"

before_script:
    - cmake .

script:
    - make

branches:
    only:
        - master
